name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/google-sheets-proxy .
        docker push gcr.io/${{ secrets.GCP_PROJECT }}/google-sheets-proxy

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy google-sheets-proxy --image gcr.io/${{ secrets.GCP_PROJECT }}/google-sheets-proxy --platform managed --region us-central1 --allow-unauthenticated
